
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: NFS
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/postgre
    server: 192.168.199.24
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    type: NFS
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv
  storageClassName: standard

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: YWRtaW4=
  password: YWRtaW4kMTIz